name: Lint

on:
  pull_request:
    types: [opened, synchronize]

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
      - name: Install Prettier
        run: npm install -g prettier

      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install dependencies
        run: npm install

      - name: Check code style with Prettier
        run: npm run format:check

      - name: Lint JavaScript code with ESLint
        run: npm run lint:js

      - name: Lint styles with Stylelint
        run: npm run lint:styles
